name: Build Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Clean & Setup Android
        run: |
          rm -rf android
          flutter create . --platforms=android --org=com.bella.iptv
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          sed -i 's/minSdkVersion 16/minSdkVersion 21/g' android/app/build.gradle
          sed -i 's/minSdkVersion 19/minSdkVersion 21/g' android/app/build.gradle
          sed -i 's/<application/<application android:usesCleartextTraffic="true"/g' android/app/src/main/AndroidManifest.xml
          sed -i 's/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android">/<manifest xmlns:android="http:\/\/schemas.android.com\/apk\/res\/android">\n    <uses-permission android:name="android.permission.INTERNET"\/>\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"\/>\n    <uses-feature android:name="android.software.leanback" android:required="false"\/>\n    <uses-feature android:name="android.hardware.touchscreen" android:required="false"\/>/g' android/app/src/main/AndroidManifest.xml
          sed -i '/<\/manifest>/i\    <queries>\n        <intent>\n            <action android:name="android.intent.action.DIAL" \/>\n            <data android:scheme="tel" \/>\n        <\/intent>\n        <intent>\n            <action android:name="android.intent.action.VIEW" \/>\n            <data android:scheme="https" \/>\n        <\/intent>\n    <\/queries>' android/app/src/main/AndroidManifest.xml
          sed -i '/android.intent.category.LAUNCHER/a\                <category android:name="android.intent.category.LEANBACK_LAUNCHER" \/>' android/app/src/main/AndroidManifest.xml
      - name: Install Dependencies
        run: flutter pub get
      - name: Build APK Release
        run: flutter build apk --release
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bella_IPTV_Pro_APK
          path: build/app/outputs/flutter-apk/app-release.apk
